// Install REST Client by Huachao Mao in VSCode to send these off from here

// ========== BASIC SERVER ========== //

// See if server is alive and kicking
http://localhost:3000
###


// ========== EVENTS ========== //

// Get all events
http://localhost:3000/events
###

// Get event by event id
http://localhost:3000/events/1
###

// Search for event by string
http://localhost:3000/events?search=Event
###

// Create event
POST http://localhost:3000/events HTTP/1.1
content-type: application/json

{
    "title": "Berghain 1",
    "authorEmail": "alice@prisma.io"
}
###

// Publish event
PUT http://localhost:3000/events/2/publish
###

// Delete event
DELETE http://localhost:3000/events/1 HTTP/1.1
###


// ========== USERS ========== //

// Create new user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "user8",
    "email": "user8@asdfasdfe3.de"
}
###


// ========== POSTS ========== //

// Get all posts
http://localhost:3000/posts
###

// Get post by post id
http://localhost:3000/posts/1
###

// Search for post by string
http://localhost:3000/posts?search=Hello
###

// Create post
POST http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
    "title": "Another Title",
    "authorEmail": "alice@prisma.io"
}
###

// Publish post
PUT http://localhost:3000/posts/1/publish
###

// Delete post
DELETE http://localhost:3000/posts/4 HTTP/1.1
###
