# Official Node.js image
FROM    node:20-alpine

# Set working directory inside container
WORKDIR /app

# Copy dependency files and install them
COPY    package*.json tsconfig.json ./
RUN     npm install

# Copy the rest (source files)
COPY    . .

# Build TS to JS
RUN     npm run build

# Expose the port the service listens on
# (really set in .yaml file, it's for documentation here)
EXPOSE  3000

# Start the user service
CMD ["npm", "start"]
